spring.application.name=audio-transcribe

server.port=${PORT:8080}

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB